//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpmmm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koncurs
    {
        public int ID_koncurs { get; set; }
        public string SecondName { get; set; }
        public Nullable<int> MinReyt { get; set; }
        public Nullable<int> Summa { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> Dni { get; set; }
        
    }
}
